"""Versioned PostgreSQL schema for the durable v1 relay protocol."""

SCHEMA = """
CREATE TABLE IF NOT EXISTS relay_schema(version integer PRIMARY KEY);
INSERT INTO relay_schema VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS workspaces(id text PRIMARY KEY,name text NOT NULL);
CREATE TABLE IF NOT EXISTS nodes(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),name text NOT NULL,token_hash text UNIQUE NOT NULL,revoked integer NOT NULL DEFAULT 0,last_seen double precision,snapshot text,snapshot_hash text);
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS snapshot_hash text;
CREATE INDEX IF NOT EXISTS node_workspace ON nodes(workspace_id,name,id) WHERE revoked=0;
CREATE TABLE IF NOT EXISTS devices(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),name text NOT NULL,token_hash text UNIQUE NOT NULL,revoked integer NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS device_workspace ON devices(workspace_id) WHERE revoked=0;
CREATE TABLE IF NOT EXISTS invitations(code_hash text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),expires double precision NOT NULL);
CREATE INDEX IF NOT EXISTS invitation_expiry ON invitations(expires);
CREATE TABLE IF NOT EXISTS requests(id text PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),device_id text NOT NULL REFERENCES devices(id),node_id text NOT NULL REFERENCES nodes(id),operation text NOT NULL,body_hash text NOT NULL,body_bytes bigint NOT NULL,body text NOT NULL,state text NOT NULL,result text,error text,created double precision NOT NULL,claimed double precision,updated double precision NOT NULL,expires_at double precision,result_read double precision,result_bytes bigint NOT NULL DEFAULT 0,reserved_bytes bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS request_queue ON requests(node_id,created,id) WHERE state='queued';
CREATE INDEX IF NOT EXISTS request_queue_expiry ON requests(created,id) WHERE state='queued';
CREATE INDEX IF NOT EXISTS request_claim_expiry ON requests(claimed,id) WHERE state='claimed';
CREATE INDEX IF NOT EXISTS terminal_expiry ON requests(expires_at,id) WHERE state='queued' AND expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS terminal_history ON requests(updated,id) WHERE operation='terminal_snapshot' AND state IN ('completed','failed','uncertain');
CREATE INDEX IF NOT EXISTS request_history ON requests(updated,id) WHERE body!='' AND state IN ('completed','failed','uncertain');
CREATE INDEX IF NOT EXISTS read_history_v2 ON requests(updated,id) WHERE operation IN ('inspect','history','process_output','terminal_snapshot','catalog','dirs','worktrees') AND state IN ('completed','failed','uncertain');
CREATE INDEX IF NOT EXISTS request_workspace ON requests(workspace_id,state);
CREATE TABLE IF NOT EXISTS workspace_usage(workspace_id text PRIMARY KEY REFERENCES workspaces(id),payload_bytes bigint NOT NULL DEFAULT 0,active bigint NOT NULL DEFAULT 0,reads bigint NOT NULL DEFAULT 0,mutations bigint NOT NULL DEFAULT 0,events bigint NOT NULL DEFAULT 0,push_jobs bigint NOT NULL DEFAULT 0,active_polls bigint NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS payload_shards(id integer PRIMARY KEY,payload_bytes bigint NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS relay_allocation(id integer PRIMARY KEY CHECK(id=1),global_max_bytes bigint NOT NULL,quota_shards integer NOT NULL);
CREATE TABLE IF NOT EXISTS rate_control(id integer PRIMARY KEY,entries bigint NOT NULL DEFAULT 0);
ALTER TABLE rate_control DROP CONSTRAINT IF EXISTS rate_control_id_check;
INSERT INTO rate_control(id) VALUES(1),(2) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS global_usage(id integer PRIMARY KEY CHECK(id=1),payload_bytes bigint NOT NULL DEFAULT 0,events bigint NOT NULL DEFAULT 0,push_jobs bigint NOT NULL DEFAULT 0);
INSERT INTO global_usage(id) VALUES(1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,workspace_id text NOT NULL REFERENCES workspaces(id),node_id text NOT NULL,session text NOT NULL,kind text NOT NULL,created double precision NOT NULL);
CREATE INDEX IF NOT EXISTS event_workspace ON events(workspace_id,id);
CREATE INDEX IF NOT EXISTS event_expiry ON events(created,id);
CREATE TABLE IF NOT EXISTS pushes(device_id text PRIMARY KEY REFERENCES devices(id),provider text NOT NULL,target text NOT NULL);
CREATE TABLE IF NOT EXISTS push_jobs(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,device_id text NOT NULL REFERENCES devices(id),event_id bigint NOT NULL,payload text NOT NULL,attempts integer NOT NULL DEFAULT 0,next_at double precision NOT NULL,created double precision NOT NULL,lease_token text,lease_until double precision);
CREATE INDEX IF NOT EXISTS push_device ON push_jobs(device_id,id);
CREATE INDEX IF NOT EXISTS push_ready ON push_jobs(next_at,id) WHERE attempts<5;
CREATE INDEX IF NOT EXISTS push_expiry ON push_jobs(created,id);
CREATE TABLE IF NOT EXISTS poll_credentials(role text NOT NULL,credential_id text NOT NULL,active bigint NOT NULL DEFAULT 0,PRIMARY KEY(role,credential_id));
CREATE TABLE IF NOT EXISTS poll_leases(id text PRIMARY KEY,role text NOT NULL,credential_id text NOT NULL,workspace_id text NOT NULL REFERENCES workspaces(id),expires double precision NOT NULL);
CREATE INDEX IF NOT EXISTS poll_expiry ON poll_leases(expires,id);
CREATE TABLE IF NOT EXISTS rate_limits(key text PRIMARY KEY,count bigint NOT NULL,expires double precision NOT NULL,bucket integer NOT NULL DEFAULT 1);
ALTER TABLE rate_limits ADD COLUMN IF NOT EXISTS bucket integer NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS rate_expiry ON rate_limits(expires,key);
"""

from .routes import SCHEMA as ROUTE_SCHEMA
SCHEMA += """
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS computer_id TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS machine_id TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS manifest_hash TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS target_computer_id TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS target_machine_id TEXT;
ALTER TABLE requests ADD COLUMN IF NOT EXISTS route_id TEXT;
""" + ROUTE_SCHEMA
